[package]
name = "avrio_rpc"
version = "0.1.0"
authors = ["Arielh25 <areilhurdle@gmail.com>", "TheDevMinerTV <tobigames200@gmail.com>"]
edition = "2018"
[dependencys]
serde = { version = "1.0", features = ["derive"] }
