[package]
name = "avrio_p2p"
version = "0.1.0"
authors = ["Arielh25 <areilhurdle@gmail.com>", "TheDevMinerTV <tobigames200@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.4"
avrio_config = {path = "../config"}
log = "~0.4"
rand = "~0.7.3"
serde = "~1.0.82"
serde_derive = "1.0.104"
serde_json = "~1.0.33"
unwrap = "~1.2.1"
